### ISSUE TITLE
Package is not compatible with EPIServer CMS 11

### ISSUE THREAD

**Issue by mirage-codes** [Geta/Epi.MediaReferenceSelector#5]
After upgrading to EPiServer CMS 11, the package cannot load.

**Comment by degborta** [comment]
If you have upgrade to 11.15.0  Episerver have introduced similar functionality:
https://world.episerver.com/blogs/bartosz-sekula/dates/2019/1/image-property-editor-enhancements/

This project will no further be maintained.

Thanks!
